version: '{branch}_1.0.{build}'
branches:
  except:
  - gh-pages
skip_tags: true
clone_folder: C:\gopath\src\appveyor\md2html
environment:
  GOPATH: C:\gopath
  GOVERSION: '1.11'
  GO111MODULE: 'on'
  matrix:
  - _GOOS: windows
    _GOARCH: 386
  - _GOOS: windows
    _GOARCH: amd64
  - _GOOS: linux
    _GOARCH: 386
  - _GOOS: linux
    _GOARCH: amd64
init:
  - go version
  - go env
install:
  - set PATH=%PATH%;%GOPATH%\bin
before_build:
  - set GOOS=%_GOOS%
  - set GOARCH=%_GOARCH%
build_script:
  - go build
after_build:
  - for /f "usebackq" %%e in (`go env GOEXE`) do @ set GOEXE=%%e
  - 7z a md2html_%GOOS%_%GOARCH%.zip md2html%GOEXE%
artifacts:
- path: md2html_$(GOOS)_$(GOARCH).zip
  name: md2html
deploy:
- provider: GitHub
  auth_token:
    secure: VHpPnf0g2XPt+pjaVagSyiXZHq3e2se6bHIz/E3e9JonBVe2S3hRx5hEg7xcWTIJ
  artifact: md2html_$(GOOS)_$(GOARCH).zip
  draft: true
