version: '{branch}_1.0.{build}'
branches:
  except:
  - gh-pages
skip_tags: true
clone_folder: C:\gopath\src\appveyor\md2html
environment:
  GOPATH: C:\gopath
  matrix:
  - GOOS: windows
    GOARCH: 386
  - GOOS: windows
    GOARCH: amd64
  - GOOS: linux
    GOARCH: 386
  - GOOS: linux
    GOARCH: amd64
install:
- cmd: >-
    go env

    go get -u github.com/golang/dep/...

    set PATH=%PATH%;%GOPATH%\bin\$(GOOS)_$(GOARCH)

    dir %GOPATH%\bin\$(GOOS)_$(GOARCH)
before_build:
- cmd: >-
    go env

    echo %PATH%
build_script:
- cmd: >-
    dir %GOPATH%\bin

    dir %GOROOT%\bin

    go get -d github.com/nocd5/md2html

    dep ensure

    go build
after_build:
- cmd: >-
    for /f "usebackq" %%e in (`go env GOEXE`) do @ set GOEXE=%%e

    7z a md2html_%GOOS%_%GOARCH%.zip md2html%GOEXE%
artifacts:
- path: md2html_$(GOOS)_$(GOARCH).zip
  name: md2html
deploy:
- provider: GitHub
  auth_token:
    secure: msXREOrf813FAzkJvvU5/QyYe/ZKzMQhMx9Zv3XD7NAHHAR+Zf1ueMDi6MsQmFlt
  artifact: md2html_$(GOOS)_$(GOARCH).zip
  draft: true
