version: '{branch}_1.0.{build}'
branches:
  except:
  - gh-pages
skip_tags: true
clone_folder: C:\gopath\src\appveyor\md2html
environment:
  GOPATH: C:\gopath
  matrix:
  - _GOOS: windows
    _GOARCH: 386
  - _GOOS: windows
    _GOARCH: amd64
  - _GOOS: linux
    _GOARCH: 386
  - _GOOS: linux
    _GOARCH: amd64
init:
- cmd: >-
    go env
install:
- cmd: >-
    go get -u github.com/golang/dep/...

    set PATH=%PATH%;%GOPATH%\bin
before_build:
- cmd: >-
    set GOOS=%_GOOS%
    set GOARCH=%_GOARCH%
build_script:
- cmd: >-
    dep ensure

    go build
after_build:
- cmd: >-
    for /f "usebackq" %%e in (`go env GOEXE`) do @ set GOEXE=%%e

    7z a md2html_%GOOS%_%GOARCH%.zip md2html%GOEXE%
artifacts:
- path: md2html_$(GOOS)_$(GOARCH).zip
  name: md2html
deploy:
- provider: GitHub
  auth_token:
    secure: msXREOrf813FAzkJvvU5/QyYe/ZKzMQhMx9Zv3XD7NAHHAR+Zf1ueMDi6MsQmFlt
  artifact: md2html_$(GOOS)_$(GOARCH).zip
  draft: true
